### PR TITLE
MNEMONIC-729: Configure the log4jv2.xml with correct settings that align with current log4jv1 settings

### PR DESCRIPTION
**Pull request by jxjlearn**
Signed-off-by: Xiaojin Jiao <xjiao@apache.org>

### CODE REVIEW

**Review by yzz127 — CHANGES_REQUESTED** [review]
The changes look good, but we will need to configure the xml for the whole project instead of just one module. Could you please make the changes for other modules as well? Thanks

**Comment by jxjlearn** [comment]
> The changes look good, but we will need to configure the xml for the whole project instead of just one module. Could you please make the changes for other modules as well? Thanks

Thanks for the feedback. I updated the PR with other required changes. Please take a look. Thanks.

**Review by yzz127 — APPROVED** [review]
Looks good, thanks!

**Review by bigdata-memory — APPROVED** [review]
+1, thanks.

**Pull request merged**
