### PR TITLE
MNEMONIC-711: Clean obsoleted content in redis memory service gradle file

### PR DESCRIPTION
**Pull request by byl5088**
Please review the changes on removing obsoleted content

### CODE REVIEW

**Review by yzz127 — CHANGES_REQUESTED** [review]
The code changes are ok, but the commit history is not clean. Please rebase to latest commit and then making the code changes. Thanks!

**Comment by byl5088** [comment]
Hi Yanhui, I have modified my commit history so there are no merges now. Please review again. - Bing

**Review by bigdata-memory — APPROVED** [review]
+1, thanks.

**Review by yzz127 — APPROVED** [review]
Thanks!

**Pull request merged**
