### PR TITLE
MNEMONIC-780: Remove a redundant env setting from dockerfile

### PR DESCRIPTION
**Pull request by jxjlearn**

### CODE REVIEW

**Review by bigdata-memory — APPROVED** [review]
+1, thanks.

**Review by katarinaking — APPROVED** [review]
Looks good to me.

**Comment by bigdata-memory** [comment]
Looks there is a conflict with previous commit, please resolve it, thanks.

**Comment by bigdata-memory** [comment]
You can rebase your local git repo with latest commit of upstream repo and then push it with option "-f", thanks.

**Review by bigdata-memory — APPROVED** [review]

**Pull request merged**
