### PR TITLE
MNEMONIC-670: Remove warnings caused by maven-shade-plugin

### PR DESCRIPTION
**Pull request by rhythmwind**
Signed-off-by: Zhen Li <rhythmwind@gmail.com>

### CODE REVIEW

**Review by bigdata-memory — APPROVED** [review]
It is good to remove all of those warnings caused by the use of shade plugins, thanks +1

**Review by yzz127 — CHANGES_REQUESTED** [review]
Seems some issue during building test, could you please double check?

**Comment by bigdata-memory** [comment]
This PR can build on my local machine, so the failing check might be caused by other factors, I think it could be possible to merge it first, thanks.

**Comment by yzz127** [comment]
Ok, will identify the issue after code merge.

**Pull request merged**
