### PR TITLE
MNEMONIC-641: [JDK14] Specify JDK14 to build project in Maven

### PR DESCRIPTION
**Pull request by rhythmwind**
Signed-off-by: Zhen Li <rhythmwind@gmail.com>

### CODE REVIEW

**Review by yzz127 — COMMENTED** [review]
Seems JDK target version is causing CI build error. I submitted the JIRA ticket for this issue. Please hold, thanks!

**Review by bigdata-memory — APPROVED** [review]
LGTM, thanks

**Comment by yzz127** [comment]
MNEMONIC-643 is merged, and it should solve this CI error. Please trigger the CI again. Thanks

**Comment by bigdata-memory** [comment]
Sorry, It would rely on ticket MNEMONIC-645 as well, We expect there are other issues once applied this PR. I think it could be better if we have another topic branch to merge the JDK14 related PRs and merge it to main branch when it got stabilized.

**Comment by yzz127** [comment]
Agreed with Gary, will merge this PR

**Pull request merged**
