### PR TITLE
Issue 572: Create build.gradle for subproject mnemonic-benches (sort bench)

### PR DESCRIPTION
**Pull request by jxjlearn**

### CODE REVIEW

**Review by yzz127 — CHANGES_REQUESTED** [review]
The commit history seems messed up, could you please correct it? Thanks

**Comment by jxjlearn** [comment]
Yes, somehow it got messed up. I have updated the PR. Thanks.

**Review by yzz127 — APPROVED** [review]
Looks good, my +1. Thanks

**Review by bigdata-memory — APPROVED** [review]
LGTM, +1, thanks.

**Pull request merged**
